apiVersion: v1          
kind: Pod          
metadata:          
  creationTimestamp: null          
  labels:          
    run: busyboxtest          
  name: busyboxtest          
  namespace: flag-reciever          
spec:          
  securityContext:          
    runAsNonRoot: true          
    runAsUser: 1000          
    seccompProfile:          
      type: RuntimeDefault          
  containers:          
  - image: busybox          
    name: busyboxtest          
    args: [/bin/sh, -c, 'nc -lp 8080']          
    ports:          
      - containerPort: 8080          
        name: http-web-svc          
    securityContext:          
        allowPrivilegeEscalation: false          
        capabilities:          
          drop:          
            - ALL          
    resources:          
        limits:          
          cpu: "100m"          
          memory: "0Mi"          
        requests:          
          cpu: "100m"          
          memory: "0Mi"          
  dnsPolicy: ClusterFirst          
  restartPolicy: Always          
status: {}
