apiVersion: v1          
kind: Service          
metadata:          
  name: my-custom-service          
  namespace: flag-reciever          
spec:          
  externalIPs:          
  - 1.1.1.1          
  ports:          
    - port: 80          
      targetPort: 8080          
  selector:          
    run: busyboxtest
